# Generated by Django 2.1.7 on 2019-03-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='calorie',
        ),
        migrations.AddField(
            model_name='diet',
            name='Calorific_Value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='Item',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='Quantity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='categories',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
