# Generated by Django 2.1.7 on 2019-04-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0002_auto_20190308_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diet',
            old_name='Calorific_Value',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='diet',
            old_name='Item',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='diet',
            old_name='Quantity',
            new_name='disease',
        ),
        migrations.RenameField(
            model_name='diet',
            old_name='categories',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='diet',
            name='height',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='weight',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
