# Generated by Django 2.1.7 on 2019-04-06 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0003_auto_20190406_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diet',
            old_name='username',
            new_name='users',
        ),
    ]
