# Generated by Django 2.1.7 on 2019-04-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0004_auto_20190406_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='age',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='height',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='weight',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
