# Generated by Django 2.1.7 on 2019-04-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0005_auto_20190418_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='BMI',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
