# Generated by Django 2.1.7 on 2019-04-18 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0006_diet_bmi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diet',
            old_name='BMI',
            new_name='bmi',
        ),
    ]
