# Generated by Django 2.1.7 on 2019-04-18 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0007_auto_20190418_0451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diet',
            old_name='bmi',
            new_name='BMI',
        ),
    ]
