# Generated by Django 2.1.7 on 2019-04-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0008_auto_20190418_0502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BMI', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='diet',
            name='BMI',
        ),
    ]
