# Generated by Django 2.1.7 on 2019-04-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0009_auto_20190418_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defg', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Calculation',
            new_name='BodyMassIndex',
        ),
    ]
