# Generated by Django 2.2 on 2019-04-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0010_auto_20190418_0534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diet',
            old_name='disease',
            new_name='diabetes',
        ),
        migrations.AddField(
            model_name='diet',
            name='heart',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='kidney',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
