# Generated by Django 2.2 on 2019-04-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0012_auto_20190419_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='diabetes',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='heart',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='kidney',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
